version: "3"
services:
  modelapi:
    build:
      context: .
      dockerfile: modelapi_dockerfile
    ports: 
      - "8000:8000"
    env_file:
      - env/mongo.env
      - env/queue.env

  modelworker:
    build: 
      context: .
      dockerfile: model_dockerfile
    env_file:
      - env/mongo.env
      - env/queue.env

  frontend:
    build: 
      context: .
      dockerfile: frontend_dockerfile
    ports: 
      - "3000:3000"
    env_file:
      - env/modelapi.env
    