version: "0.1"
services:
  modelapi:
    image: "modelapi_image"
    ports: 
      - "8000:8000"

  modelworker:
    image: "model_image"

  frontend:
    image: "node_image"
    ports: 
      - "3000:3000"

    