site_name: Sentiment Analysis
site_description: Sentiment Analysis of Tweets
site_author: Momal Ijaz
site_url: https://github.com/Momilijaz96/SentimentAnalysis
nav:
  - Home: index.md
  - workflows:
      - main: sentiment_analysis/main.md
  - sentiment_analysis:
      - data: sentiment_analysis/data.md
      - evaluate: sentiment_analysis/evaluate.md
      - predict: sentiment_analysis/predict.md
      - train: sentiment_analysis/train.md
      - utils: sentiment_analysis/utils.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - . # reload docs for any file changes
