apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-prod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-prod
  template:
    metadata:
      labels:
        app: frontend-prod
    spec:
      containers:
        - name: frontend-prod
          image: momil56/sentiment_analysis:frontend-prod
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-service
spec:
  selector:
    app: frontend-prod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
