apiVersion: apps/v1
kind: Deployment
metadata:
  name: storageworker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storageworker
  template:
    metadata:
      labels:
        app: storageworker
    spec:
      containers:
        - name: storageworker
          image: momil56/sentiment_analysis:storageworker
          envFrom:
            - configMapRef:
                name: queue-configmap
            - configMapRef:
                name: storage-configmap
          imagePullPolicy: Always
